export { HomePage } from './HomePage';
export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { GoalPage } from './GoalPage';
export { ProfilePage } from './ProfilePage';
export { SettingsPage } from './SettingsPage';
export { NewGoalPage } from './NewGoalPage';
export { CreateGoalPage } from './CreateGoalPage';
export { GoalsPage } from './GoalsPage';
